# Form implementation generated from reading ui file 'Ui_MainWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets

from utils import get_resource_path


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(980, 660)
        MainWindow.setMinimumSize(QtCore.QSize(980, 660))
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(9, 9, 9, 9)
        self.horizontalLayout.setSpacing(9)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setStyleSheet("QFrame{\n"
"    border:0px solid red;\n"
"    border-radius:28px\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.frame_main = QtWidgets.QFrame(parent=self.frame)
        self.frame_main.setStyleSheet("QFrame{\n"
"    background-color: rgb(245, 249, 254);\n"
"    border:0px solid red;\n"
"    border-radius:30px\n"
"}")
        self.frame_main.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_main.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_main.setObjectName("frame_main")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.frame_main)
        self.verticalLayout_30.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout_30.setSpacing(0)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        self.frame_9 = QtWidgets.QFrame(parent=self.frame_main)
        self.frame_9.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_9.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_9.setObjectName("frame_9")
        self.horizontalLayout_33 = QtWidgets.QHBoxLayout(self.frame_9)
        self.horizontalLayout_33.setContentsMargins(12, 0, 12, 0)
        self.horizontalLayout_33.setSpacing(12)
        self.horizontalLayout_33.setObjectName("horizontalLayout_33")
        self.widget_logo = QtWidgets.QWidget(parent=self.frame_9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(30)
        sizePolicy.setVerticalStretch(30)
        sizePolicy.setHeightForWidth(self.widget_logo.sizePolicy().hasHeightForWidth())
        self.widget_logo.setSizePolicy(sizePolicy)
        self.widget_logo.setMinimumSize(QtCore.QSize(38, 38))
        self.widget_logo.setMaximumSize(QtCore.QSize(38, 38))
        self.widget_logo.setStyleSheet("QWidget {\n"
f"    image: url({get_resource_path('resources/img/logo.svg')});\n"
"}")
        self.widget_logo.setObjectName("widget_logo")
        self.horizontalLayout_33.addWidget(self.widget_logo)
        self.label_54 = QtWidgets.QLabel(parent=self.frame_9)
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(22)
        font.setBold(False)
        self.label_54.setFont(font)
        self.label_54.setStyleSheet("QLabel {\n"
"    color: rgb(0, 0, 0);\n"
"}")
        self.label_54.setObjectName("label_54")
        self.horizontalLayout_33.addWidget(self.label_54)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem)
        self.toolButton_setting = QtWidgets.QToolButton(parent=self.frame_9)
        self.toolButton_setting.setMinimumSize(QtCore.QSize(36, 36))
        self.toolButton_setting.setMaximumSize(QtCore.QSize(36, 36))
        self.toolButton_setting.setStyleSheet("QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"    spacing: 4px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgba(150, 150, 150, 80);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    color: #999999;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"    subcontrol-position: right center;\n"
"    subcontrol-origin: padding;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}")
        self.toolButton_setting.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(get_resource_path("resources/img/窗口控制/窗口控制-设置.svg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_setting.setIcon(icon)
        self.toolButton_setting.setIconSize(QtCore.QSize(20, 20))
        self.toolButton_setting.setObjectName("toolButton_setting")
        self.horizontalLayout_33.addWidget(self.toolButton_setting)
        self.toolButton_mini = QtWidgets.QToolButton(parent=self.frame_9)
        self.toolButton_mini.setMinimumSize(QtCore.QSize(36, 36))
        self.toolButton_mini.setMaximumSize(QtCore.QSize(36, 36))
        self.toolButton_mini.setStyleSheet("QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"    spacing: 4px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgba(150, 150, 150, 80);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    color: #999999;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"    subcontrol-position: right center;\n"
"    subcontrol-origin: padding;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}")
        self.toolButton_mini.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(get_resource_path("resources/img/窗口控制/窗口控制-最小化.svg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_mini.setIcon(icon1)
        self.toolButton_mini.setIconSize(QtCore.QSize(22, 22))
        self.toolButton_mini.setObjectName("toolButton_mini")
        self.horizontalLayout_33.addWidget(self.toolButton_mini)
        self.toolButton_close = QtWidgets.QToolButton(parent=self.frame_9)
        self.toolButton_close.setMinimumSize(QtCore.QSize(36, 36))
        self.toolButton_close.setMaximumSize(QtCore.QSize(36, 36))
        self.toolButton_close.setStyleSheet("QToolButton {\n"
"    background: transparent;\n"
"    border: none;\n"
"    padding: 0;\n"
"    spacing: 4px;\n"
"    color: #333333;\n"
"}\n"
"\n"
"QToolButton:hover {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 9px;\n"
"}\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: rgba(150, 150, 150, 80);\n"
"}\n"
"\n"
"QToolButton:disabled {\n"
"    color: #999999;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QToolButton::menu-indicator {\n"
"    image: none;\n"
"    subcontrol-position: right center;\n"
"    subcontrol-origin: padding;\n"
"    width: 8px;\n"
"    height: 8px;\n"
"}")
        self.toolButton_close.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(get_resource_path("resources/img/窗口控制/窗口控制-关闭.svg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.toolButton_close.setIcon(icon2)
        self.toolButton_close.setIconSize(QtCore.QSize(22, 22))
        self.toolButton_close.setObjectName("toolButton_close")
        self.horizontalLayout_33.addWidget(self.toolButton_close)
        self.verticalLayout_30.addWidget(self.frame_9)
        self.horizontalLayout_32 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_32.setSpacing(12)
        self.horizontalLayout_32.setObjectName("horizontalLayout_32")
        self.frame_7 = QtWidgets.QFrame(parent=self.frame_main)
        self.frame_7.setStyleSheet("")
        self.frame_7.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_7.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_7.setObjectName("frame_7")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.frame_7)
        self.verticalLayout_29.setSpacing(9)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.verticalFrame = QtWidgets.QFrame(parent=self.frame_7)
        self.verticalFrame.setStyleSheet("QFrame {\n"
"    background-color: rgb(255, 255, 255);\n"
"    border-radius: 12px;\n"
"}")
        self.verticalFrame.setObjectName("verticalFrame")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalFrame)
        self.verticalLayout.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setContentsMargins(0, -1, -1, 9)
        self.horizontalLayout_3.setSpacing(0)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label = QtWidgets.QLabel(parent=self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(16)
        font.setBold(False)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout_3.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.label_6 = QtWidgets.QLabel(parent=self.verticalFrame)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_6.sizePolicy().hasHeightForWidth())
        self.label_6.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("")
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setContentsMargins(6, 2, 18, 9)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.lineEdit_src_folder = QtWidgets.QLineEdit(parent=self.verticalFrame)
        self.lineEdit_src_folder.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #e2e8f0;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 12px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 10px 14px;\n"
"    background: #ffffff;\n"
"    color: #334155;\n"
"    font-size: 15px;\n"
"    transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #94a3b8;\n"
"    background: #f8fafc;\n"
"    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(60, 145, 255);\n"
"    background: #ffffff;\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 3px rgba(85, 0, 255, 0.3), 0 1px 3px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background: #f8fafc;\n"
"    color: #94a3b8;\n"
"    border-color: #e2e8f0;\n"
"    box-shadow: none;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QLineEdit:read-only {\n"
"    background: #f1f5f9;\n"
"    color: #64748b;\n"
"    border-color: #e2e8f0;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #94a3b8;\n"
"    opacity: 0.8;\n"
"}\n"
"\n"
"QLineEdit:valid {\n"
"    border-color: #10b981;\n"
"}\n"
"\n"
"QLineEdit:invalid {\n"
"    border-color: #ef4444;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    letter-spacing: 0.15em;\n"
"}\n"
"\n"
"QLineEdit[frame=\"false\"] {\n"
"    padding: 8px 12px;\n"
"}")
        self.lineEdit_src_folder.setObjectName("lineEdit_src_folder")
        self.horizontalLayout_4.addWidget(self.lineEdit_src_folder)
        self.pushButton_src_folder = QtWidgets.QPushButton(parent=self.verticalFrame)
        self.pushButton_src_folder.setMinimumSize(QtCore.QSize(56, 43))
        self.pushButton_src_folder.setMaximumSize(QtCore.QSize(56, 43))
        self.pushButton_src_folder.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 145, 255);\n"
"    color: white;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 12px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(90, 170, 255);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 3px 6px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 120, 240);\n"
"    transform: translateY(1px);\n"
"    box-shadow: none;\n"
"}")
        self.pushButton_src_folder.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(get_resource_path("resources/img/ui/文件夹.svg")), QtGui.QIcon.Mode.Normal, QtGui.QIcon.State.Off)
        self.pushButton_src_folder.setIcon(icon3)
        self.pushButton_src_folder.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_src_folder.setObjectName("pushButton_src_folder")
        self.horizontalLayout_4.addWidget(self.pushButton_src_folder)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.label_7 = QtWidgets.QLabel(parent=self.verticalFrame)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setContentsMargins(6, 2, 18, 9)
        self.horizontalLayout_8.setSpacing(0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.lineEdit_dst_folder = QtWidgets.QLineEdit(parent=self.verticalFrame)
        self.lineEdit_dst_folder.setStyleSheet("QLineEdit {\n"
"    border: 1px solid #e2e8f0;\n"
"    border-top-left-radius: 12px;\n"
"    border-top-right-radius: 0px;\n"
"    border-bottom-left-radius: 12px;\n"
"    border-bottom-right-radius: 0px;\n"
"    padding: 10px 14px;\n"
"    background: #ffffff;\n"
"    color: #334155;\n"
"    font-size: 15px;\n"
"    transition: all 0.2s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 1px 2px rgba(0, 0, 0, 0.05);\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #94a3b8;\n"
"    background: #f8fafc;\n"
"    box-shadow: 0 1px 3px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: rgb(60, 145, 255);\n"
"    background: #ffffff;\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 3px rgba(85, 0, 255, 0.3), 0 1px 3px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    background: #f8fafc;\n"
"    color: #94a3b8;\n"
"    border-color: #e2e8f0;\n"
"    box-shadow: none;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QLineEdit:read-only {\n"
"    background: #f1f5f9;\n"
"    color: #64748b;\n"
"    border-color: #e2e8f0;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QLineEdit::placeholder {\n"
"    color: #94a3b8;\n"
"    opacity: 0.8;\n"
"}\n"
"\n"
"QLineEdit:valid {\n"
"    border-color: #10b981;\n"
"}\n"
"\n"
"QLineEdit:invalid {\n"
"    border-color: #ef4444;\n"
"}\n"
"\n"
"QLineEdit[echoMode=\"2\"] {\n"
"    letter-spacing: 0.15em;\n"
"}\n"
"\n"
"QLineEdit[frame=\"false\"] {\n"
"    padding: 8px 12px;\n"
"}")
        self.lineEdit_dst_folder.setObjectName("lineEdit_dst_folder")
        self.horizontalLayout_8.addWidget(self.lineEdit_dst_folder)
        self.pushButton_dst_folder = QtWidgets.QPushButton(parent=self.verticalFrame)
        self.pushButton_dst_folder.setMinimumSize(QtCore.QSize(56, 43))
        self.pushButton_dst_folder.setMaximumSize(QtCore.QSize(56, 43))
        self.pushButton_dst_folder.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 145, 255);\n"
"    color: white;\n"
"    border-top-left-radius: 0px;\n"
"    border-top-right-radius: 12px;\n"
"    border-bottom-left-radius: 0px;\n"
"    border-bottom-right-radius: 12px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(90, 170, 255);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 3px 6px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(30, 120, 240);\n"
"    transform: translateY(1px);\n"
"    box-shadow: none;\n"
"}")
        self.pushButton_dst_folder.setText("")
        self.pushButton_dst_folder.setIcon(icon3)
        self.pushButton_dst_folder.setIconSize(QtCore.QSize(26, 26))
        self.pushButton_dst_folder.setObjectName("pushButton_dst_folder")
        self.horizontalLayout_8.addWidget(self.pushButton_dst_folder)
        self.verticalLayout.addLayout(self.horizontalLayout_8)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(-1, 0, -1, 6)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.line = QtWidgets.QFrame(parent=self.verticalFrame)
        self.line.setMinimumSize(QtCore.QSize(0, 2))
        self.line.setMaximumSize(QtCore.QSize(16777215, 2))
        self.line.setStyleSheet("background: rgb(234, 234, 234);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.verticalLayout.addLayout(self.verticalLayout_2)
        self.label_8 = QtWidgets.QLabel(parent=self.verticalFrame)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_7.setSpacing(19)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.copy_radio = QtWidgets.QRadioButton(parent=self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.copy_radio.setFont(font)
        self.copy_radio.setObjectName("copy_radio")
        self.horizontalLayout_7.addWidget(self.copy_radio)
        self.move_radio = QtWidgets.QRadioButton(parent=self.verticalFrame)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.move_radio.setFont(font)
        self.move_radio.setObjectName("move_radio")
        self.horizontalLayout_7.addWidget(self.move_radio)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout_29.addWidget(self.verticalFrame)
        self.horizontalFrame_3 = QtWidgets.QFrame(parent=self.frame_7)
        self.horizontalFrame_3.setObjectName("horizontalFrame_3")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.horizontalFrame_3)
        self.horizontalLayout_5.setContentsMargins(24, 0, 24, 0)
        self.horizontalLayout_5.setSpacing(16)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalFrame_6 = QtWidgets.QFrame(parent=self.horizontalFrame_3)
        self.horizontalFrame_6.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:12px")
        self.horizontalFrame_6.setObjectName("horizontalFrame_6")
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout(self.horizontalFrame_6)
        self.horizontalLayout_12.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.widget_6 = QtWidgets.QWidget(parent=self.horizontalFrame_6)
        self.widget_6.setMinimumSize(QtCore.QSize(58, 58))
        self.widget_6.setMaximumSize(QtCore.QSize(58, 58))
        self.widget_6.setStyleSheet("QWidget {\n"
f"    image: url({get_resource_path('resources/img/ui/已处理.svg')});\n"
"}")
        self.widget_6.setObjectName("widget_6")
        self.horizontalLayout_12.addWidget(self.widget_6)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label_13 = QtWidgets.QLabel(parent=self.horizontalFrame_6)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(False)
        self.label_13.setFont(font)
        self.label_13.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_13.setObjectName("label_13")
        self.verticalLayout_6.addWidget(self.label_13)
        self.processed_label = QtWidgets.QLabel(parent=self.horizontalFrame_6)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(24)
        font.setBold(True)
        self.processed_label.setFont(font)
        self.processed_label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 173, 58);\n"
"}")
        self.processed_label.setObjectName("processed_label")
        self.verticalLayout_6.addWidget(self.processed_label)
        self.horizontalLayout_12.addLayout(self.verticalLayout_6)
        self.horizontalLayout_5.addWidget(self.horizontalFrame_6)
        self.horizontalFrame_5 = QtWidgets.QFrame(parent=self.horizontalFrame_3)
        self.horizontalFrame_5.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:12px")
        self.horizontalFrame_5.setObjectName("horizontalFrame_5")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.horizontalFrame_5)
        self.horizontalLayout_10.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.widget_4 = QtWidgets.QWidget(parent=self.horizontalFrame_5)
        self.widget_4.setMinimumSize(QtCore.QSize(58, 58))
        self.widget_4.setMaximumSize(QtCore.QSize(58, 58))
        self.widget_4.setStyleSheet("QWidget {\n"
f"    image: url({get_resource_path('resources/img/ui/总文件数.svg')});\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.horizontalLayout_10.addWidget(self.widget_4)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setContentsMargins(0, -1, -1, -1)
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_9 = QtWidgets.QLabel(parent=self.horizontalFrame_5)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_9.setObjectName("label_9")
        self.verticalLayout_4.addWidget(self.label_9)
        self.total_files_label = QtWidgets.QLabel(parent=self.horizontalFrame_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Preferred, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.total_files_label.sizePolicy().hasHeightForWidth())
        self.total_files_label.setSizePolicy(sizePolicy)
        self.total_files_label.setMaximumSize(QtCore.QSize(16777215, 16777215))
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(24)
        font.setBold(True)
        self.total_files_label.setFont(font)
        self.total_files_label.setStyleSheet("QLabel {\n"
"    color: rgb(255, 64, 178);\n"
"}")
        self.total_files_label.setObjectName("total_files_label")
        self.verticalLayout_4.addWidget(self.total_files_label)
        self.horizontalLayout_10.addLayout(self.verticalLayout_4)
        self.horizontalLayout_5.addWidget(self.horizontalFrame_5)
        self.horizontalFrame_7 = QtWidgets.QFrame(parent=self.horizontalFrame_3)
        self.horizontalFrame_7.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:12px")
        self.horizontalFrame_7.setObjectName("horizontalFrame_7")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.horizontalFrame_7)
        self.horizontalLayout_13.setContentsMargins(16, -1, 16, -1)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.widget_7 = QtWidgets.QWidget(parent=self.horizontalFrame_7)
        self.widget_7.setMinimumSize(QtCore.QSize(58, 58))
        self.widget_7.setMaximumSize(QtCore.QSize(58, 58))
        self.widget_7.setStyleSheet("QWidget {\n"
f"    image: url({get_resource_path('resources/img/ui/成功.svg')});\n"
"}")
        self.widget_7.setObjectName("widget_7")
        self.horizontalLayout_13.addWidget(self.widget_7)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.label_15 = QtWidgets.QLabel(parent=self.horizontalFrame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_15.setObjectName("label_15")
        self.verticalLayout_7.addWidget(self.label_15)
        self.success_label = QtWidgets.QLabel(parent=self.horizontalFrame_7)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(24)
        font.setBold(True)
        self.success_label.setFont(font)
        self.success_label.setStyleSheet("QLabel {\n"
"    color: rgb(66, 225, 155);\n"
"}")
        self.success_label.setObjectName("success_label")
        self.verticalLayout_7.addWidget(self.success_label)
        self.horizontalLayout_13.addLayout(self.verticalLayout_7)
        self.horizontalLayout_5.addWidget(self.horizontalFrame_7)
        self.horizontalFrame_8 = QtWidgets.QFrame(parent=self.horizontalFrame_3)
        self.horizontalFrame_8.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"border-radius:12px")
        self.horizontalFrame_8.setObjectName("horizontalFrame_8")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.horizontalFrame_8)
        self.horizontalLayout_14.setContentsMargins(16, -1, -1, -1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.widget_8 = QtWidgets.QWidget(parent=self.horizontalFrame_8)
        self.widget_8.setMinimumSize(QtCore.QSize(58, 58))
        self.widget_8.setMaximumSize(QtCore.QSize(58, 58))
        self.widget_8.setStyleSheet("QWidget {\n"
f"    image: url({get_resource_path('resources/img/ui/失败.svg')});\n"
"}")
        self.widget_8.setObjectName("widget_8")
        self.horizontalLayout_14.addWidget(self.widget_8)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label_17 = QtWidgets.QLabel(parent=self.horizontalFrame_8)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_17.setFont(font)
        self.label_17.setStyleSheet("color: rgb(147, 147, 147);")
        self.label_17.setObjectName("label_17")
        self.verticalLayout_8.addWidget(self.label_17)
        self.failed_label = QtWidgets.QLabel(parent=self.horizontalFrame_8)
        font = QtGui.QFont()
        font.setFamily("等线")
        font.setPointSize(24)
        font.setBold(True)
        self.failed_label.setFont(font)
        self.failed_label.setStyleSheet("QLabel {\n"
"    color: rgb(245, 67, 65);\n"
"}")
        self.failed_label.setObjectName("failed_label")
        self.verticalLayout_8.addWidget(self.failed_label)
        self.horizontalLayout_14.addLayout(self.verticalLayout_8)
        self.horizontalLayout_5.addWidget(self.horizontalFrame_8)
        self.verticalLayout_29.addWidget(self.horizontalFrame_3)
        self.frame_8 = QtWidgets.QFrame(parent=self.frame_7)
        self.frame_8.setStyleSheet("QFrame{\n"
"    background-color: rgb(255, 255, 255);\n"
"border:0px solid red;\n"
"border-radius:12px\n"
"}")
        self.frame_8.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_8.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_8.setObjectName("frame_8")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.frame_8)
        self.verticalLayout_36.setContentsMargins(12, 12, 12, 12)
        self.verticalLayout_36.setSpacing(8)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(6, -1, 6, -1)
        self.horizontalLayout_9.setSpacing(12)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(parent=self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.progressBar = QtWidgets.QProgressBar(parent=self.frame_8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.progressBar.sizePolicy().hasHeightForWidth())
        self.progressBar.setSizePolicy(sizePolicy)
        self.progressBar.setMinimumSize(QtCore.QSize(0, 0))
        self.progressBar.setMaximumSize(QtCore.QSize(684, 16777215))
        self.progressBar.setStyleSheet("QProgressBar {\n"
"    border: 1px solid rgba(60, 145, 255, 0.5); \n"
"    border-radius: 8px;\n"
"    background-color: #ffffff;\n"
"    text-align: center;\n"
"    font-size: 14px;\n"
"    color: rgb(0, 0, 0);\n"
"    padding: 2px;\n"
"}\n"
"\n"
"QProgressBar::chunk {\n"
"    background-color: rgba(60, 145, 255, 0.6);\n"
"    width: 10px;\n"
"    margin: 0.5px;\n"
"    border-radius: 7px;\n"
"    transition: width 0.5s ease-in-out;\n"
"}\n"
"\n"
"QProgressBar:completed {\n"
"    background-color: rgb(60, 145, 255);\n"
"    border-color: rgb(60, 145, 255);\n"
"}")
        self.progressBar.setProperty("value", 0)
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_9.addWidget(self.progressBar)
        self.pushButton_start = QtWidgets.QPushButton(parent=self.frame_8)
        self.pushButton_start.setStyleSheet("QPushButton {\n"
"    background-color: rgb(60, 145, 255);\n"
"    color: white;\n"
"    border-radius: 4px;\n"
"    padding: 8px 16px;\n"
"    font-size: 14px;\n"
"    font-weight: 500;\n"
"    border: none;\n"
"    transition: all 0.2s ease;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 3px 6px rgba(0, 0, 0, 0.1);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: rgb(40, 125, 220);\n"
"    transform: translateY(1px);\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background-color: rgb(140, 190, 255);\n"
"    color: rgb(220, 220, 220);\n"
"    transform: none;\n"
"    box-shadow: none;\n"
"    opacity: 0.7;\n"
"}\n"
"\n"
"QPushButton#startBtn {\n"
"    background-color: rgb(60, 145, 255);\n"
"    padding: 10px 20px;\n"
"    font-size: 15px;\n"
"}\n"
"\n"
"QPushButton#browseBtn {\n"
"    background-color: rgba(60, 145, 255, 0.9);\n"
"    padding: 6px 12px;\n"
"    font-size: 13px;\n"
"}\n"
"\n"
"QPushButton#stopBtn {\n"
"    background-color: rgb(230, 50, 80);\n"
"}\n"
"\n"
"QPushButton#stopBtn:hover {\n"
"    background-color: rgb(240, 60, 90);\n"
"}\n"
"\n"
"QPushButton#stopBtn:pressed {\n"
"    background-color: rgb(210, 40, 70);\n"
"}")
        self.pushButton_start.setObjectName("pushButton_start")
        self.horizontalLayout_9.addWidget(self.pushButton_start)
        self.verticalLayout_36.addLayout(self.horizontalLayout_9)
        self.textEdit_log = QtWidgets.QTextEdit(parent=self.frame_8)
        self.textEdit_log.setStyleSheet("QTextEdit {\n"
"    border: 1px solid #e2e8f0;\n"
"    border-radius: 12px;\n"
"    padding: 4px;\n"
"    background-color: #ffffff;\n"
"    color: #334155;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar:vertical {\n"
"    width: 6px;\n"
"    background-color: #f8fafc;\n"
"    margin: 8px 0px 8px 0px;\n"
"    border-radius: 3px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:vertical {\n"
"    background-color: rgb(60, 145, 255);\n"
"    border-radius: 3px;\n"
"    min-height: 20px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-line:vertical,\n"
"QTextEdit QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::add-page:vertical,\n"
"QTextEdit QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"QTextEdit QScrollBar::handle:vertical:hover {\n"
"    background-color: rgb(85, 170, 255);\n"
"}\n"
"\n"
"QTextEdit QScrollBar:up-arrow:vertical,\n"
"QTextEdit QScrollBar:down-arrow:vertical {\n"
"    height: 0px;\n"
"    width: 0px;\n"
"    background: none;\n"
"}")
        self.textEdit_log.setObjectName("textEdit_log")
        self.verticalLayout_36.addWidget(self.textEdit_log)
        self.verticalLayout_29.addWidget(self.frame_8)
        self.verticalLayout_29.setStretch(2, 1)
        self.horizontalLayout_32.addWidget(self.frame_7)
        self.horizontalLayout_32.setStretch(0, 1)
        self.verticalLayout_30.addLayout(self.horizontalLayout_32)
        self.horizontalLayout_2.addWidget(self.frame_main)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout.addWidget(self.frame)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_54.setText(_translate("MainWindow", "LeafView-RailwayOCR"))
        self.label.setText(_translate("MainWindow", "文件夹设置"))
        self.label_6.setText(_translate("MainWindow", "源文件夹"))
        self.lineEdit_src_folder.setPlaceholderText(_translate("MainWindow", "待处理文件夹（默认包含子文件夹）"))
        self.label_7.setText(_translate("MainWindow", "目标文件夹"))
        self.lineEdit_dst_folder.setPlaceholderText(_translate("MainWindow", "存放分类后的结果"))
        self.label_8.setText(_translate("MainWindow", "处理模式"))
        self.copy_radio.setText(_translate("MainWindow", "复制文件"))
        self.move_radio.setText(_translate("MainWindow", "移动文件"))
        self.label_13.setText(_translate("MainWindow", "已处理"))
        self.processed_label.setText(_translate("MainWindow", "null"))
        self.label_9.setText(_translate("MainWindow", "总文件数"))
        self.total_files_label.setText(_translate("MainWindow", "null"))
        self.label_15.setText(_translate("MainWindow", "成功"))
        self.success_label.setText(_translate("MainWindow", "null"))
        self.label_17.setText(_translate("MainWindow", "失败"))
        self.failed_label.setText(_translate("MainWindow", "null"))
        self.label_2.setText(_translate("MainWindow", "处理结果"))
        self.pushButton_start.setText(_translate("MainWindow", "开始分类"))
