# Form implementation generated from reading ui file 'Ui_SettingWindow.ui'
#
# Created by: PyQt6 UI code generator 6.4.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_SettingWindow(object):
    def setupUi(self, SettingWindow):
        SettingWindow.setObjectName("SettingWindow")
        SettingWindow.resize(932, 598)
        self.centralwidget = QtWidgets.QWidget(parent=SettingWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.main_frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.main_frame.setStyleSheet("QFrame{\n"
"background: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                          stop: 0 rgba(255, 255, 255, 0.98), \n"
"                          stop: 1 rgba(248, 250, 255, 0.95));\n"
"border: 1px solid rgba(30, 131, 255, 0.12);\n"
"border-radius: 0px;\n"
"box-shadow: 0 12px 40px rgba(30, 131, 255, 0.1);\n"
"backdrop-filter: blur(12px);\n"
"transition: all 0.4s cubic-bezier(0.4, 0, 0.2, 1);\n"
"}\n"
"\n"
"QFrame:hover {\n"
"    box-shadow: 0 16px 48px rgba(30, 131, 255, 0.15);\n"
"    transform: translateY(-2px);\n"
"}\n"
"\n"
"/* 添加现代滚动条样式 */\n"
"QScrollBar:vertical {\n"
"    border: none;\n"
"    background: transparent;\n"
"    width: 10px;\n"
"    margin: 2px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical {\n"
"    background: rgba(30, 131, 255, 0.4);\n"
"    border-radius: 5px;\n"
"    min-height: 30px;\n"
"}\n"
"\n"
"QScrollBar::handle:vertical:hover {\n"
"    background: rgba(30, 131, 255, 0.6);\n"
"}\n"
"\n"
"QScrollBar::add-line:vertical, QScrollBar::sub-line:vertical {\n"
"    height: 0px;\n"
"}\n"
"\n"
"QScrollBar::add-page:vertical, QScrollBar::sub-page:vertical {\n"
"    background: none;\n"
"}\n"
"\n"
"/* 添加现代分隔线样式 */\n"
"QFrame[line=\"true\"] {\n"
"    background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                              stop:0 rgba(30, 131, 255, 0.1), \n"
"                              stop:0.5 rgba(30, 131, 255, 0.3),\n"
"                              stop:1 rgba(30, 131, 255, 0.1));\n"
"    border: none;\n"
"    height: 1px;\n"
"}")
        self.main_frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.main_frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.main_frame.setObjectName("main_frame")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.main_frame)
        self.horizontalLayout_18.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_18.setSpacing(20)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setContentsMargins(24, 24, 24, 24)
        self.verticalLayout_2.setSpacing(16)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setContentsMargins(-1, -1, -1, 24)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(18)
        self.label.setFont(font)
        self.label.setStyleSheet("color: #1e83ff;\n"
"background: linear-gradient(135deg, #1e83ff 0%, #0052cc 100%);\n"
"-webkit-background-clip: text;\n"
"-webkit-text-fill-color: transparent;\n"
"background-clip: text;\n"
"text-shadow: 0 2px 4px rgba(30, 131, 255, 0.2);")
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(16)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_2 = QtWidgets.QLabel(parent=self.main_frame)
        self.label_2.setMinimumSize(QtCore.QSize(188, 0))
        self.label_2.setMaximumSize(QtCore.QSize(188, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(False)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("color: #2d3748;\n"
"background: transparent;\n"
"border: none;")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_9.addWidget(self.label_2)
        self.lineEdit_BAIDU_API_KEY = QtWidgets.QLineEdit(parent=self.main_frame)
        self.lineEdit_BAIDU_API_KEY.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.lineEdit_BAIDU_API_KEY.setFont(font)
        self.lineEdit_BAIDU_API_KEY.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"    padding: 7px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    selection-background-color: rgba(30, 131, 255, 0.3);\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #a0aec0;\n"
"    background-color: #f7fafc;\n"
"    box-shadow: 0 4px 12px rgba(30, 131, 255, 0.12);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #1e83ff;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 0 4px rgba(30, 131, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-color: #e2e8f0;\n"
"    background-color: #f8f9fa;\n"
"    color: #a0aec0;\n"
"}\n"
"\n"
"/* 现代占位文本样式 */\n"
"QLineEdit::placeholder {\n"
"    color: #a0aec0;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    opacity: 0.8;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* 错误状态样式 */\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: #e53e3e;\n"
"    background-color: #fff5f5;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"]:focus {\n"
"    box-shadow: 0 0 0 4px rgba(229, 62, 62, 0.15);\n"
"}")
        self.lineEdit_BAIDU_API_KEY.setObjectName("lineEdit_BAIDU_API_KEY")
        self.horizontalLayout_9.addWidget(self.lineEdit_BAIDU_API_KEY)
        self.horizontalLayout_2.addLayout(self.horizontalLayout_9)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(12)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(parent=self.main_frame)
        self.label_3.setMinimumSize(QtCore.QSize(188, 0))
        self.label_3.setMaximumSize(QtCore.QSize(188, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("color: #2d3748;\n"
"background: transparent;\n"
"border: none;")
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.lineEdit_BAIDU_SECRET_KEY = QtWidgets.QLineEdit(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.lineEdit_BAIDU_SECRET_KEY.setFont(font)
        self.lineEdit_BAIDU_SECRET_KEY.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"    padding: 7px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    selection-background-color: rgba(30, 131, 255, 0.3);\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #a0aec0;\n"
"    background-color: #f7fafc;\n"
"    box-shadow: 0 4px 12px rgba(30, 131, 255, 0.12);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #1e83ff;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 0 4px rgba(30, 131, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-color: #e2e8f0;\n"
"    background-color: #f8f9fa;\n"
"    color: #a0aec0;\n"
"}\n"
"\n"
"/* 现代占位文本样式 */\n"
"QLineEdit::placeholder {\n"
"    color: #a0aec0;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    opacity: 0.8;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* 错误状态样式 */\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: #e53e3e;\n"
"    background-color: #fff5f5;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"]:focus {\n"
"    box-shadow: 0 0 0 4px rgba(229, 62, 62, 0.15);\n"
"}")
        self.lineEdit_BAIDU_SECRET_KEY.setObjectName("lineEdit_BAIDU_SECRET_KEY")
        self.horizontalLayout_3.addWidget(self.lineEdit_BAIDU_SECRET_KEY)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_3)
        self.verticalLayout_2.addLayout(self.horizontalLayout_5)
        self.line_3 = QtWidgets.QFrame(parent=self.main_frame)
        self.line_3.setMinimumSize(QtCore.QSize(0, 1))
        self.line_3.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line_3.setStyleSheet("background: qlineargradient(x1:0, y1:0, x2:1, y2:0,\n"
"                              stop:0 rgba(30, 131, 255, 0.2), \n"
"                              stop:0.5 rgba(30, 131, 255, 0.4),\n"
"                              stop:1 rgba(30, 131, 255, 0.2));\n"
"border: none;\n"
"height: 2px;")
        self.line_3.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout_2.addWidget(self.line_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setSpacing(16)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_4 = QtWidgets.QLabel(parent=self.main_frame)
        self.label_4.setMinimumSize(QtCore.QSize(188, 0))
        self.label_4.setMaximumSize(QtCore.QSize(188, 16777215))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("color: #2d3748;\n"
"background: transparent;\n"
"border: none;")
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_10.addWidget(self.label_4)
        self.lineEdit_ALI_APPCODE = QtWidgets.QLineEdit(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.lineEdit_ALI_APPCODE.setFont(font)
        self.lineEdit_ALI_APPCODE.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"    padding: 7px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    selection-background-color: rgba(30, 131, 255, 0.3);\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #a0aec0;\n"
"    background-color: #f7fafc;\n"
"    box-shadow: 0 4px 12px rgba(30, 131, 255, 0.12);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #1e83ff;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 0 4px rgba(30, 131, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-color: #e2e8f0;\n"
"    background-color: #f8f9fa;\n"
"    color: #a0aec0;\n"
"}\n"
"\n"
"/* 现代占位文本样式 */\n"
"QLineEdit::placeholder {\n"
"    color: #a0aec0;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    opacity: 0.8;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* 错误状态样式 */\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: #e53e3e;\n"
"    background-color: #fff5f5;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"]:focus {\n"
"    box-shadow: 0 0 0 4px rgba(229, 62, 62, 0.15);\n"
"}")
        self.lineEdit_ALI_APPCODE.setPlaceholderText("阿里云code")
        self.lineEdit_ALI_APPCODE.setObjectName("lineEdit_ALI_APPCODE")
        self.horizontalLayout_10.addWidget(self.lineEdit_ALI_APPCODE)
        self.horizontalLayout_4.addLayout(self.horizontalLayout_10)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(parent=self.main_frame)
        self.line.setMinimumSize(QtCore.QSize(0, 1))
        self.line.setMaximumSize(QtCore.QSize(16777215, 1))
        self.line.setStyleSheet("background: rgba(30, 131, 255, 0.3);")
        self.line.setFrameShape(QtWidgets.QFrame.Shape.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Shadow.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setContentsMargins(-1, 0, 0, 0)
        self.horizontalLayout_6.setSpacing(24)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setSpacing(16)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_7 = QtWidgets.QLabel(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet("color: #2d3748;\n"
"background: transparent;\n"
"border: none;")
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_7.addWidget(self.label_7)
        self.spinBox_CONCURRENCY = QtWidgets.QSpinBox(parent=self.main_frame)
        self.spinBox_CONCURRENCY.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.spinBox_CONCURRENCY.setFont(font)
        self.spinBox_CONCURRENCY.setStyleSheet("QSpinBox {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"    padding: 6px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border-color: #a0aec0;\n"
"    background-color: #f7fafc;\n"
"    box-shadow: 0 4px 12px rgba(30, 131, 255, 0.12);\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border-color: #1e83ff;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 0 4px rgba(30, 131, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"\n"
"QSpinBox:disabled {\n"
"    border-color: #e2e8f0;\n"
"    background-color: #f8f9fa;\n"
"    color: #a0aec0;\n"
"}\n"
"\n"
"/* 现代按钮样式 */\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #e2e8f0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-position: top right;\n"
"    height: 50%;\n"
"    border-bottom: 1px solid #e2e8f0;\n"
"    border-top-right-radius: 9px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-position: bottom right;\n"
"    height: 50%;\n"
"    border-bottom-right-radius: 9px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: rgba(30, 131, 255, 0.08);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed {\n"
"    background-color: rgba(30, 131, 255, 0.15);\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QSpinBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    background: none;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAiIGhlaWdodD0iMTAiIHZpZXdCb3g9IjAgMCAxMCAxMCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA0TDEwIDlMMCA5WiIgc3Ryb2tlPSIjNjc3MjgwIiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIi8+PC9zdmc+);\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAiIGhlaWdodD0iMTAiIHZpZXdCb3g9IjAgMCAxMCAxMCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA2TDAgMUwxMCAxWiIgc3Ryb2tlPSIjNjc3MjgwIiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIi8+PC9zdmc+);\n"
"}")
        self.spinBox_CONCURRENCY.setMinimum(1)
        self.spinBox_CONCURRENCY.setMaximum(32)
        self.spinBox_CONCURRENCY.setObjectName("spinBox_CONCURRENCY")
        self.horizontalLayout_7.addWidget(self.spinBox_CONCURRENCY)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_14.setSpacing(16)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_6 = QtWidgets.QLabel(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("color: #2d3748;\n"
"background: transparent;\n"
"border: none;")
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_14.addWidget(self.label_6)
        self.spinBox_RETRY_TIMES = QtWidgets.QSpinBox(parent=self.main_frame)
        self.spinBox_RETRY_TIMES.setMinimumSize(QtCore.QSize(120, 0))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.spinBox_RETRY_TIMES.setFont(font)
        self.spinBox_RETRY_TIMES.setStyleSheet("QSpinBox {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"    padding: 6px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    min-width: 100px;\n"
"}\n"
"\n"
"QSpinBox:hover {\n"
"    border-color: #a0aec0;\n"
"    background-color: #f7fafc;\n"
"    box-shadow: 0 4px 12px rgba(30, 131, 255, 0.12);\n"
"}\n"
"\n"
"QSpinBox:focus {\n"
"    border-color: #1e83ff;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 0 4px rgba(30, 131, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"\n"
"QSpinBox:disabled {\n"
"    border-color: #e2e8f0;\n"
"    background-color: #f8f9fa;\n"
"    color: #a0aec0;\n"
"}\n"
"\n"
"/* 现代按钮样式 */\n"
"QSpinBox::up-button, QSpinBox::down-button {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center right;\n"
"    width: 28px;\n"
"    border-left: 1px solid #e2e8f0;\n"
"    background-color: transparent;\n"
"}\n"
"\n"
"QSpinBox::up-button {\n"
"    subcontrol-position: top right;\n"
"    height: 50%;\n"
"    border-bottom: 1px solid #e2e8f0;\n"
"    border-top-right-radius: 9px;\n"
"}\n"
"\n"
"QSpinBox::down-button {\n"
"    subcontrol-position: bottom right;\n"
"    height: 50%;\n"
"    border-bottom-right-radius: 9px;\n"
"}\n"
"\n"
"QSpinBox::up-button:hover, QSpinBox::down-button:hover {\n"
"    background-color: rgba(30, 131, 255, 0.08);\n"
"}\n"
"\n"
"QSpinBox::up-button:pressed, QSpinBox::down-button:pressed {\n"
"    background-color: rgba(30, 131, 255, 0.15);\n"
"}\n"
"\n"
"QSpinBox::up-arrow, QSpinBox::down-arrow {\n"
"    width: 10px;\n"
"    height: 10px;\n"
"    background: none;\n"
"}\n"
"\n"
"QSpinBox::up-arrow {\n"
"    image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAiIGhlaWdodD0iMTAiIHZpZXdCb3g9IjAgMCAxMCAxMCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA0TDEwIDlMMCA5WiIgc3Ryb2tlPSIjNjc3MjgwIiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIi8+PC9zdmc+);\n"
"}\n"
"\n"
"QSpinBox::down-arrow {\n"
"    image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTAiIGhlaWdodD0iMTAiIHZpZXdCb3g9IjAgMCAxMCAxMCIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNNSA2TDAgMUwxMCAxWiIgc3Ryb2tlPSIjNjc3MjgwIiBzdHJva2Utd2lkdGg9IjEuNSIgc3Ryb2tlLWxpbmVjYXA9InJvdW5kIiBzdHJva2UtbGluZWpvaW49InJvdW5kIi8+PC9zdmc+);\n"
"}")
        self.spinBox_RETRY_TIMES.setMinimum(3)
        self.spinBox_RETRY_TIMES.setMaximum(30)
        self.spinBox_RETRY_TIMES.setSingleStep(1)
        self.spinBox_RETRY_TIMES.setProperty("value", 3)
        self.spinBox_RETRY_TIMES.setObjectName("spinBox_RETRY_TIMES")
        self.horizontalLayout_14.addWidget(self.spinBox_RETRY_TIMES)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_14)
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_16.setContentsMargins(-1, -1, 0, -1)
        self.horizontalLayout_16.setSpacing(16)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.label_11 = QtWidgets.QLabel(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet("color: #2d3748;\n"
"background: transparent;\n"
"border: none;")
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_16.addWidget(self.label_11)
        self.comboBox_mode = QtWidgets.QComboBox(parent=self.main_frame)
        self.comboBox_mode.setStyleSheet("QComboBox {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"    padding: 6px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QComboBox:hover {\n"
"    border-color: #a0aec0;\n"
"    background-color: #f7fafc;\n"
"    box-shadow: 0 4px 12px rgba(30, 131, 255, 0.12);\n"
"}\n"
"\n"
"QComboBox:focus {\n"
"    border-color: #1e83ff;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 0 4px rgba(30, 131, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox:disabled {\n"
"    border-color: #e2e8f0;\n"
"    background-color: #f8f9fa;\n"
"    color: #a0aec0;\n"
"}\n"
"\n"
"/* 现代下拉按钮样式 */\n"
"QComboBox::drop-down {\n"
"    subcontrol-origin: border;\n"
"    subcontrol-position: center right;\n"
"    width: 32px;\n"
"    border-left: 1px solid #e2e8f0;\n"
"    background-color: transparent;\n"
"    border-top-right-radius: 9px;\n"
"    border-bottom-right-radius: 9px;\n"
"}\n"
"\n"
"QComboBox::drop-down:hover {\n"
"    background-color: rgba(30, 131, 255, 0.08);\n"
"}\n"
"\n"
"QComboBox::drop-down:pressed {\n"
"    background-color: rgba(30, 131, 255, 0.15);\n"
"}\n"
"\n"
"/* 现代下拉箭头样式 */\n"
"QComboBox::down-arrow {\n"
"    image: url(data:image/svg+xml;base64,PHN2ZyB3aWR0aD0iMTIiIGhlaWdodD0iMTIiIHZpZXdCb3g9IjAgMCAxMiAxMiIgZmlsbD0ibm9uZSIgeG1sbnM9Imh0dHA6Ly93d3cudzMub3JnLzIwMDAvc3ZnIj48cGF0aCBkPSJNMiA0LjVMNiA4LjVMMTAgNC41IiBzdHJva2U9IiM2NzcyODAiIHN0cm9rZS13aWR0aD0iMS41IiBzdHJva2UtbGluZWNhcD0icm91bmQiIHN0cm9rZS1saW5lam9pbj0icm91bmQiLz48L3N2Zz4=);\n"
"    width: 12px;\n"
"    height: 12px;\n"
"}\n"
"\n"
"/* 现代下拉列表样式 */\n"
"QComboBox QAbstractItemView {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 8px;\n"
"    background-color: #ffffff;\n"
"    padding: 8px 0;\n"
"    margin: 4px 0 0 0;\n"
"    box-shadow: 0 8px 24px rgba(0, 0, 0, 0.12);\n"
"    outline: none;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item {\n"
"    height: 36px;\n"
"    padding: 8px 16px;\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:selected {\n"
"    background-color: rgba(30, 131, 255, 0.12);\n"
"    color: #1e83ff;\n"
"    font-weight: 500;\n"
"}\n"
"\n"
"QComboBox QAbstractItemView::item:hover {\n"
"    background-color: rgba(30, 131, 255, 0.08);\n"
"}")
        self.comboBox_mode.setObjectName("comboBox_mode")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.comboBox_mode.addItem("")
        self.horizontalLayout_16.addWidget(self.comboBox_mode)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_16)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem)
        self.pushButton_Password = QtWidgets.QPushButton(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_Password.setFont(font)
        self.pushButton_Password.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 18px;\n"
"    background: #258fff; /* 纯蓝色主色调 */\n"
"    color: white;\n"
"    letter-spacing: 0.5px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 4px 14px rgba(37, 143, 255, 0.3);\n"
"    text-transform: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #3a99ff; /* 亮一点的蓝色 */\n"
"    transform: translateY(-2px);\n"
"    box-shadow: 0 6px 16px rgba(37, 143, 255, 0.4);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0a66e0; /* 深一点的蓝色 */\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 2px 8px rgba(37, 143, 255, 0.3);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #e2e8f0; /* 禁用状态的灰色 */\n"
"    color: #a0aec0;\n"
"    box-shadow: 0 2px 6px rgba(160, 174, 192, 0.15);\n"
"    transform: none;\n"
"}\n"
"\n"
"/* 聚焦状态 - 增强可访问性 */\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 3px rgba(37, 143, 255, 0.3),\n"
"                0 4px 14px rgba(37, 143, 255, 0.3);\n"
"}\n"
"\n"
"/* 次要按钮变体 */\n"
"QPushButton[secondary=\"true\"] {\n"
"    background: transparent;\n"
"    border: 1.5px solid #258fff;\n"
"    color: #258fff;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QPushButton[secondary=\"true\"]:hover {\n"
"    background: rgba(37, 143, 255, 0.1);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 12px rgba(37, 143, 255, 0.15);\n"
"}\n"
"\n"
"QPushButton[secondary=\"true\"]:pressed {\n"
"    background: rgba(37, 143, 255, 0.2);\n"
"    transform: translateY(0px);\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"/* 成功按钮变体 */\n"
"QPushButton[success=\"true\"] {\n"
"    background: #38b2ac; /* 纯绿色调 */\n"
"    box-shadow: 0 4px 16px rgba(56, 178, 172, 0.3);\n"
"}\n"
"\n"
"QPushButton[success=\"true\"]:hover {\n"
"    background: #48bfa7; /* 亮一点的绿色 */\n"
"    box-shadow: 0 6px 16px rgba(56, 178, 172, 0.4);\n"
"}\n"
"\n"
"QPushButton[success=\"true\"]:pressed {\n"
"    background: #2d978f; /* 深一点的绿色 */\n"
"    box-shadow: 0 2px 8px rgba(56, 178, 172, 0.3);\n"
"}\n"
"")
        self.pushButton_Password.setObjectName("pushButton_Password")
        self.horizontalLayout_6.addWidget(self.pushButton_Password)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setSpacing(16)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_8 = QtWidgets.QLabel(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("color: #2d3748;\n"
"background: transparent;\n"
"border: none;")
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_8.addWidget(self.label_8)
        self.lineEdit_RE = QtWidgets.QLineEdit(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(False)
        self.lineEdit_RE.setFont(font)
        self.lineEdit_RE.setStyleSheet("QLineEdit {\n"
"    border: 2px solid #e2e8f0;\n"
"    border-radius: 10px;\n"
"    padding: 7px 8px;\n"
"    background-color: #ffffff;\n"
"    color: #2d3748;\n"
"    font-size: 14px;\n"
"    font-weight: 400;\n"
"    transition: all 0.3s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    selection-background-color: rgba(30, 131, 255, 0.3);\n"
"    min-height: 24px;\n"
"}\n"
"\n"
"QLineEdit:hover {\n"
"    border-color: #a0aec0;\n"
"    background-color: #f7fafc;\n"
"    box-shadow: 0 4px 12px rgba(30, 131, 255, 0.12);\n"
"}\n"
"\n"
"QLineEdit:focus {\n"
"    border-color: #1e83ff;\n"
"    background-color: #ffffff;\n"
"    box-shadow: 0 0 0 4px rgba(30, 131, 255, 0.15);\n"
"    outline: none;\n"
"}\n"
"\n"
"QLineEdit:disabled {\n"
"    border-color: #e2e8f0;\n"
"    background-color: #f8f9fa;\n"
"    color: #a0aec0;\n"
"}\n"
"\n"
"/* 现代占位文本样式 */\n"
"QLineEdit::placeholder {\n"
"    color: #a0aec0;\n"
"    font-style: normal;\n"
"    font-weight: 400;\n"
"    opacity: 0.8;\n"
"    font-size: 14px;\n"
"}\n"
"\n"
"/* 错误状态样式 */\n"
"QLineEdit[error=\"true\"] {\n"
"    border-color: #e53e3e;\n"
"    background-color: #fff5f5;\n"
"}\n"
"\n"
"QLineEdit[error=\"true\"]:focus {\n"
"    box-shadow: 0 0 0 4px rgba(229, 62, 62, 0.15);\n"
"}")
        self.lineEdit_RE.setObjectName("lineEdit_RE")
        self.horizontalLayout_8.addWidget(self.lineEdit_RE)
        self.verticalLayout_2.addLayout(self.horizontalLayout_8)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        self.verticalLayout_2.addItem(spacerItem1)
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Policy.Expanding, QtWidgets.QSizePolicy.Policy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem2)
        self.pushButton_save = QtWidgets.QPushButton(parent=self.main_frame)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButton_save.setFont(font)
        self.pushButton_save.setStyleSheet("QPushButton {\n"
"    border: none;\n"
"    border-radius: 6px;\n"
"    padding: 8px 18px;\n"
"    background: #258fff; /* 纯蓝色主色调 */\n"
"    color: white;\n"
"    letter-spacing: 0.5px;\n"
"    transition: all 0.25s cubic-bezier(0.4, 0, 0.2, 1);\n"
"    box-shadow: 0 4px 14px rgba(37, 143, 255, 0.3);\n"
"    text-transform: none;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background: #3a99ff; /* 亮一点的蓝色 */\n"
"    transform: translateY(-2px);\n"
"    box-shadow: 0 6px 16px rgba(37, 143, 255, 0.4);\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background: #0a66e0; /* 深一点的蓝色 */\n"
"    transform: translateY(1px);\n"
"    box-shadow: 0 2px 8px rgba(37, 143, 255, 0.3);\n"
"}\n"
"\n"
"QPushButton:disabled {\n"
"    background: #e2e8f0; /* 禁用状态的灰色 */\n"
"    color: #a0aec0;\n"
"    box-shadow: 0 2px 6px rgba(160, 174, 192, 0.15);\n"
"    transform: none;\n"
"}\n"
"\n"
"/* 聚焦状态 - 增强可访问性 */\n"
"QPushButton:focus {\n"
"    outline: none;\n"
"    box-shadow: 0 0 0 3px rgba(37, 143, 255, 0.3),\n"
"                0 4px 14px rgba(37, 143, 255, 0.3);\n"
"}\n"
"\n"
"/* 次要按钮变体 */\n"
"QPushButton[secondary=\"true\"] {\n"
"    background: transparent;\n"
"    border: 1.5px solid #258fff;\n"
"    color: #258fff;\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"QPushButton[secondary=\"true\"]:hover {\n"
"    background: rgba(37, 143, 255, 0.1);\n"
"    transform: translateY(-1px);\n"
"    box-shadow: 0 4px 12px rgba(37, 143, 255, 0.15);\n"
"}\n"
"\n"
"QPushButton[secondary=\"true\"]:pressed {\n"
"    background: rgba(37, 143, 255, 0.2);\n"
"    transform: translateY(0px);\n"
"    box-shadow: none;\n"
"}\n"
"\n"
"/* 成功按钮变体 */\n"
"QPushButton[success=\"true\"] {\n"
"    background: #38b2ac; /* 纯绿色调 */\n"
"    box-shadow: 0 4px 16px rgba(56, 178, 172, 0.3);\n"
"}\n"
"\n"
"QPushButton[success=\"true\"]:hover {\n"
"    background: #48bfa7; /* 亮一点的绿色 */\n"
"    box-shadow: 0 6px 16px rgba(56, 178, 172, 0.4);\n"
"}\n"
"\n"
"QPushButton[success=\"true\"]:pressed {\n"
"    background: #2d978f; /* 深一点的绿色 */\n"
"    box-shadow: 0 2px 8px rgba(56, 178, 172, 0.3);\n"
"}\n"
"")
        self.pushButton_save.setObjectName("pushButton_save")
        self.horizontalLayout_15.addWidget(self.pushButton_save)
        self.verticalLayout_2.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_18.addLayout(self.verticalLayout_2)
        self.verticalLayout.addWidget(self.main_frame)
        SettingWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(SettingWindow)
        QtCore.QMetaObject.connectSlotsByName(SettingWindow)

    def retranslateUi(self, SettingWindow):
        _translate = QtCore.QCoreApplication.translate
        SettingWindow.setWindowTitle(_translate("SettingWindow", "RailwayOCR - 设置"))
        self.label.setText(_translate("SettingWindow", "RailwayOCR 设置"))
        self.label_2.setText(_translate("SettingWindow", "BAIDU_API_KEY"))
        self.lineEdit_BAIDU_API_KEY.setPlaceholderText(_translate("SettingWindow", "百度千帆KEY"))
        self.label_3.setText(_translate("SettingWindow", "BAIDU_SECRET_KEY"))
        self.lineEdit_BAIDU_SECRET_KEY.setPlaceholderText(_translate("SettingWindow", "百度千帆密钥"))
        self.label_4.setText(_translate("SettingWindow", "ALI_APPCODE"))
        self.label_7.setText(_translate("SettingWindow", "线程并发数"))
        self.label_6.setText(_translate("SettingWindow", "出错重试数"))
        self.label_11.setText(_translate("SettingWindow", "识别模式"))
        self.comboBox_mode.setItemText(0, _translate("SettingWindow", "本地自研"))
        self.comboBox_mode.setItemText(1, _translate("SettingWindow", "本地飞桨"))
        self.comboBox_mode.setItemText(2, _translate("SettingWindow", "百度千帆"))
        self.comboBox_mode.setItemText(3, _translate("SettingWindow", "阿里百炼"))
        self.pushButton_Password.setText(_translate("SettingWindow", "启动密码"))
        self.label_8.setText(_translate("SettingWindow", "RE（识别结果校验）"))
        self.lineEdit_RE.setPlaceholderText(_translate("SettingWindow", "输入正则表达式"))
        self.pushButton_save.setText(_translate("SettingWindow", "保存设置"))
